server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
        health-indicator:
          enabled: false
    gateway:
      routes:
        - id: menu-service
          uri: http://menu-service:8081
          predicates:
            - Path=/api/menu,/api/menu/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/api/orders,/api/orders/**
          filters:
            - StripPrefix=1
        - id: inventory-service
          uri: http://inventory-service:8083
          predicates:
            - Path=/api/inventory,/api/inventory/**
          filters:
            - StripPrefix=1
        - id: kitchen-service
          uri: http://kitchen-service:8084
          predicates:
            - Path=/api/kitchen,/api/kitchen/**
          filters:
            - StripPrefix=1
        - id: delivery-service
          uri: http://delivery-service:8085
          predicates:
            - Path=/api/delivery,/api/delivery/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: http://notification-service:8086
          predicates:
            - Path=/api/notifications,/api/notifications/**
          filters:
            - StripPrefix=1

management:
  health:
    discovery:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
